services:
  music-parser:
    build:
      context: .
      dockerfile: Dockerfile
    image: music-parser:latest
    container_name: music-parser
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - OUTPUT_DIR=${OUTPUT_DIR:-/music}
      - OMNIVORE_IMPORT_DIR=${OMNIVORE_IMPORT_DIR:-/omnivore/inbox}
    volumes:
      - ${MUSIC_DIR:-./music}:/music
      - ${OMNIVORE_IMPORT_HOST_DIR:-./omnivore/inbox}:/omnivore/inbox
    ports:
      - "8000:8000"
